# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appvahed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdl_vahed',
            name='lname',
            field=models.CharField(default='', max_length=128, verbose_name='\u0646\u0627\u0645 \u062e\u0644\u0646\u0648\u0627\u062f\u06af\u06cc'),
            preserve_default=False,
        ),
    ]
