# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appvahed', '0003_auto_20160202_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdl_sakhtemoun',
            name='name',
            field=models.CharField(max_length=128, verbose_name='\u0646\u0627\u0645'),
        ),
        migrations.AlterField(
            model_name='mdl_vahed',
            name='lname',
            field=models.CharField(max_length=128, verbose_name='\u0646\u0627\u0645 \u062e\u0627\u0646\u0648\u0627\u062f\u06af\u06cc'),
        ),
        migrations.AlterField(
            model_name='mdl_vahed',
            name='name',
            field=models.CharField(max_length=128, verbose_name='\u0646\u0627\u0645'),
        ),
        migrations.AlterField(
            model_name='mdl_vahed',
            name='sakhtemoun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appvahed.mdl_sakhtemoun', verbose_name='\u0646\u0627\u0645 \u0633\u0627\u062e\u062a\u0645\u0627\u0646'),
        ),
    ]
