# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 16:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appvahed', '0004_auto_20160205_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdl_vahed',
            name='complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mdl_vahed',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
