# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appvahed', '0006_remove_mdl_vahed_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdl_vahed',
            name='complete',
        ),
    ]
