# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appvahed', '0010_auto_20160319_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdl_sakhtemoun',
            name='tabaghe',
            field=models.CharField(max_length=128, null=True, verbose_name='\u062a\u0639\u062f\u0627\u062f \u0637\u0628\u0642\u0647'),
        ),
        migrations.AddField(
            model_name='mdl_sakhtemoun',
            name='tedad',
            field=models.CharField(max_length=128, null=True, verbose_name='\u062a\u0639\u062f\u0627\u062f \u0648\u0627\u062d\u062f'),
        ),
        migrations.AddField(
            model_name='mdl_sakhtemoun',
            name='voroudi',
            field=models.CharField(max_length=128, null=True, verbose_name='\u062a\u0639\u062f\u0627\u062f \u0648\u0631\u0648\u062f\u06cc'),
        ),
    ]
